export const portfolioProjects = [
  {
    _id: "portfolioProject.clinia",
    _type: "portfolioProject",
    title: "Clinia",
    id: { _type: "slug", current: "clinia" },
    group: "portfolio",
    featured: true,
    order: 10,
    tags: ["AI, Saúde, CRM", "Em andamento"],
    description: "Site, Plataforma, Design System",
    href: "/clinia",
    type: "Web app",
    status: "Em andamento",
    summary: "Produto de saúde digital com CRM, experiências com IA e design system.",
    deliverables: ["UI", "UX", "Design System", "AI", "Research"],
  },
  {
    _id: "portfolioProject.talqui",
    _type: "portfolioProject",
    title: "Talqui",
    id: { _type: "slug", current: "talqui" },
    group: "portfolio",
    featured: true,
    order: 20,
    tags: ["AI, Provedores, Chat", "Em andamento"],
    description: "Site, Plataforma, Design System",
    href: "/cases/talqui",
    type: "Web app",
    status: "Em andamento",
    summary: "Plataforma de atendimento com IA, redesign, design system e site em Framer.",
    deliverables: ["UI", "UX", "Design System", "No code", "AI"],
  },
  {
    _id: "portfolioProject.petrobras",
    _type: "portfolioProject",
    title: "Petrobras",
    id: { _type: "slug", current: "petrobras" },
    group: "portfolio",
    featured: true,
    order: 30,
    tags: ["Institucional", "2022 - 2024"],
    description: "Site, Portal de Conteúdos, Design System",
    href: "/petrobras",
    type: "Site",
    status: "Case disponível",
    summary: "Portal Nossa Energia, site institucional e Design System Petrobras v2.",
    deliverables: ["UI", "UX", "Design System", "Motion", "Research"],
  },
  {
    _id: "portfolioProject.orcamais",
    _type: "portfolioProject",
    title: "Orçamais",
    id: { _type: "slug", current: "orcamais" },
    group: "portfolio",
    featured: true,
    order: 40,
    tags: ["AI, Obras, SaaS", "Em andamento"],
    description: "Plataforma de gestão de obras pela Versare",
    type: "Web app",
    status: "Em andamento",
    summary: "Plataforma de gestão de obras construída pela Versare com AI no processo.",
    deliverables: ["UI", "UX", "AI", "Design System"],
  },
  {
    _id: "portfolioProject.grupo-primo",
    _type: "portfolioProject",
    title: "Grupo Primo",
    id: { _type: "slug", current: "grupo-primo" },
    group: "portfolio",
    featured: true,
    order: 50,
    tags: ["Marketing, Finanças, Educacional", "2021 - 2022"],
    description: "Finclass, Staage, Staart, Design System e Landing Pages",
    type: "Site",
    status: "Finalizado",
    summary: "Produtos digitais de educação e conteúdo como Finclass, Staage e Staart.",
    deliverables: ["UI", "UX", "Design System"],
  },
  {
    _id: "portfolioProject.jstack",
    _type: "portfolioProject",
    title: "JStack",
    id: { _type: "slug", current: "jstack" },
    group: "portfolio",
    featured: false,
    order: 60,
    type: "Site",
    status: "Finalizado",
    summary: "Redesign institucional, posicionamento, landing pages e evolução de produto.",
    deliverables: ["UI", "UX", "No code", "Design System"],
  },
  {
    _id: "portfolioProject.grana-ai",
    _type: "portfolioProject",
    title: "Grana.ai",
    id: { _type: "slug", current: "grana-ai" },
    group: "portfolio",
    featured: false,
    order: 70,
    type: "Web app",
    status: "Versare",
    summary: "Produto financeiro com foco em clareza, jornadas e experiência de uso.",
    deliverables: ["UI", "UX", "AI"],
  },
  {
    _id: "portfolioProject.docompliance",
    _type: "portfolioProject",
    title: "Docompliance",
    id: { _type: "slug", current: "docompliance" },
    group: "portfolio",
    featured: false,
    order: 80,
    type: "Web app",
    status: "Versare",
    summary: "Plataforma jurídica com IA para fluxos de compliance e operação.",
    deliverables: ["UI", "UX", "AI", "Design System"],
  },
  {
    _id: "portfolioProject.gennio",
    _type: "portfolioProject",
    title: "Gennio",
    id: { _type: "slug", current: "gennio" },
    group: "portfolio",
    featured: false,
    order: 90,
    type: "Site",
    status: "Versare",
    summary: "Landing pages e presença digital para comunicação de produto.",
    deliverables: ["UI", "No code"],
  },
  {
    _id: "portfolioProject.velloo",
    _type: "portfolioProject",
    title: "Velloo",
    id: { _type: "slug", current: "velloo" },
    group: "portfolio",
    featured: false,
    order: 100,
    type: "App",
    status: "Versare",
    summary: "Experiência mobile com foco em interface, fluxos e produto.",
    deliverables: ["UI", "UX"],
  },
  {
    _id: "portfolioProject.marmaris",
    _type: "portfolioProject",
    title: "Marmaris",
    id: { _type: "slug", current: "marmaris" },
    group: "portfolio",
    featured: false,
    order: 110,
    type: "Site",
    status: "Versare",
    summary: "Site institucional com direção visual e experiência responsiva.",
    deliverables: ["UI", "UX", "No code"],
  },
  {
    _id: "portfolioProject.clinia-platform",
    _type: "portfolioProject",
    title: "Plataforma",
    id: { _type: "slug", current: "clinia-platform" },
    group: "clinia",
    order: 10,
    eyebrow: "Web App",
    description:
      "Nova base da plataforma Clinia: versão 2.0, onboarding, estatísticas, CRM, design system e fluxo design-to-code com Cursor e Claude.",
    href: "/cases/clinia",
    status: "Case disponível",
    type: "Web app",
  },
  {
    _id: "portfolioProject.clinia-site",
    _type: "portfolioProject",
    title: "Site",
    id: { _type: "slug", current: "clinia-site" },
    group: "clinia",
    order: 20,
    eyebrow: "Pricing",
    description: "Frente do site institucional, incluindo a página de Pricing para comunicar planos, valor e conversão comercial.",
    status: "Em andamento",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-nossa-energia",
    _type: "portfolioProject",
    title: "Nossa Energia",
    id: { _type: "slug", current: "petrobras-nossa-energia" },
    group: "petrobras",
    order: 10,
    eyebrow: "Portal de conteúdos",
    description:
      "Hub editorial da Petrobras para centralizar conteúdos institucionais, artigos e editorias usando componentes do design system.",
    href: "/cases/petrobras-nossa-energia",
    status: "Case disponível",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-design-system",
    _type: "portfolioProject",
    title: "Design System Petrobras",
    id: { _type: "slug", current: "petrobras-design-system" },
    group: "petrobras",
    order: 20,
    eyebrow: "Fundação do ecossistema",
    description:
      "Biblioteca documentada manualmente com tokens, componentes, seções, templates, motion e specs para sustentar o ecossistema digital.",
    href: "/cases/petrobras-design-system",
    status: "Case disponível",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-main-site",
    _type: "portfolioProject",
    title: "Site principal",
    id: { _type: "slug", current: "petrobras-main-site" },
    group: "petrobras",
    order: 30,
    eyebrow: "petrobras.com.br",
    description: "Experiência institucional principal conectada ao mesmo sistema visual e aos mesmos padrões de componentes.",
    status: "Em breve",
    type: "Site",
  },
];

export const caseStudies = [
  {
    _id: "caseStudy.clinia-platform",
    _type: "caseStudy",
    title: "Clinia — Plataforma 2.0",
    slug: { _type: "slug", current: "clinia" },
    client: "Clinia",
    role: "Product Design, Design System e Frontend",
    status: "Projeto em andamento",
    order: 10,
    stack: ["Figma", "shadcn", "Cursor", "Claude", "Figma MCP"],
    summary:
      "Construção da versão 2.0 da plataforma Clinia, conectando auditoria de UX, design system, shadcn customizado, protótipos reais com IA e fluxo design-to-code.",
    sections: [
      {
        _key: "contexto",
        eyebrow: "Contexto",
        title: "A versão 2.0 começou pelo entendimento do problema.",
        body: [
          "Entrei na Clinia com o objetivo de auxiliar na construção da versão 2.0 da plataforma. Antes de propor telas ou componentes, o primeiro passo foi entender as dores, gargalos e o motivo de criar uma nova versão em um produto que já existia.",
          "A nova Clinia nasce com uma tecnologia mais moderna e uma base mais escalável. A versão anterior tinha uma experiência visual menos alinhada ao momento atual da empresa e uma estrutura que dificultava evolução.",
        ],
      },
      {
        _key: "design-system",
        eyebrow: "Design System",
        title: "shadcn customizado para a identidade da Clinia.",
        body: [
          "A empresa já tinha uma direção visual desejada e alguns frameworks de front considerados. A decisão foi seguir com shadcn e adaptar toda a estrutura do Figma para atender a identidade visual da Clinia.",
          "Depois da estrutura no Figma, os mesmos componentes foram criados em código com Cursor, aproximando o trabalho de design da implementação real.",
        ],
      },
      {
        _key: "ia",
        eyebrow: "IA no processo",
        title: "Claude, Cursor e MCP do Figma no fluxo.",
        body: [
          "Usamos Claude, Cursor e MCP do Figma para criar protótipos reais sincronizados com as interfaces do Figma.",
          "O objetivo é reduzir a distância entre decisão de design, validação de fluxo e implementação.",
        ],
      },
    ],
  },
  {
    _id: "caseStudy.talqui-platform",
    _type: "caseStudy",
    title: "Talqui — Plataforma",
    slug: { _type: "slug", current: "talqui" },
    client: "Talqui",
    role: "Product Design e Design System",
    status: "Projeto em andamento",
    order: 20,
    stack: ["Figma", "Design Tokens", "Storybook", "IA"],
    summary:
      "Reconstrução da plataforma Talqui a partir de uma interface antiga criada como fork técnico, criando identidade própria, design system, tokens personalizados e documentação em Storybook.",
    sections: [
      {
        _key: "contexto",
        eyebrow: "Contexto",
        title: "A plataforma precisava deixar de parecer uma adaptação técnica.",
        body: [
          "Na Talqui, construí toda a plataforma nova, desde o Design System até as novas telas.",
          "A versão antiga era um fork de uma interface criada pelos devs. O objetivo passou a ser criar uma identidade de plataforma alinhada à marca.",
        ],
      },
      {
        _key: "escala",
        eyebrow: "Escala",
        title: "Tokens, componentes e Storybook como base viva.",
        body: [
          "Construímos o DS pensando em escala, com variáveis, design tokens e componentes preparados para novas atualizações.",
          "Os devs criaram um repositório para o design system e sincronizam a documentação com Storybook, tornando o projeto mais escalável.",
        ],
      },
    ],
    evidence: [
      {
        _key: "talqui-design-tokens",
        title: "Variáveis e tokens do Talqui DS",
        caption: "Coleções de variáveis no Figma com grupos Theme, Style, Typography e Extensions organizando os tokens semânticos da plataforma Talqui.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-cb9ebae4699bf882c7c25ee81b88c82b358c0ce9-1484x1748-png",
          },
        },
      },
      {
        _key: "talqui-checkbox-component",
        title: "Componente Checkbox no Figma",
        caption: "Componente t-field-checkbox documentado com variantes, estados (default, hover, checked, intermediate), modos light e dark, e property table completa.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-07c266b3539588596376bf83ca00d860c2c141b5-2000x1473-png",
          },
        },
      },
      {
        _key: "talqui-conversation-menu",
        title: "Componente Conversation Menu na plataforma",
        caption: "Componente t-conversation-menu com todas as variações da lista de conversas: empty, padrão, fixadas, com destaque, com notificação e skeleton (long loading).",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-66d4922a8b9fd4dc638f4f1e4a43000a0b1b62a7-2000x1473-png",
          },
        },
      },
      {
        _key: "talqui-onboarding-button",
        title: "Fluxo de onboarding e componente Button",
        caption: "Tela de cadastro da plataforma Talqui com o componente t-base-button em uso: variante Primary, estilo Filled, tamanho lg (48), com ícone e label personalizada.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-20baa3a2b02fcf13d4ff271b737358bfb521cf53-2000x1206-png",
          },
        },
      },
    ],
  },
  {
    _id: "caseStudy.petrobras-nossa-energia",
    _type: "caseStudy",
    title: "Petrobras — Nossa Energia",
    slug: { _type: "slug", current: "petrobras-nossa-energia" },
    client: "Petrobras",
    role: "Design System, UX, UI e Liferay collaboration",
    status: "Finalizado",
    order: 30,
    stack: ["Figma", "Liferay CMS", "Design System", "UX"],
    summary:
      "Portal editorial para centralizar conteúdos institucionais da Petrobras, usando o Design System Petrobras v2 e uma arquitetura de informação mais clara para publicação.",
    sections: [
      {
        _key: "desafio",
        eyebrow: "Desafio",
        title: "Centralizar conteúdos sem perder consistência.",
        body: [
          "A necessidade era centralizar conteúdos institucionais e artigos da Petrobras porque esses conteúdos estavam dispersos em canais distintos.",
          "Além disso, a transição tecnológica para CMS Liferay era essencial para oferecer aos publicadores uma experiência mais autônoma e eficiente.",
        ],
      },
      {
        _key: "solucao",
        eyebrow: "Solução",
        title: "Um hub editorial conectado ao design system.",
        body: [
          "Desenvolvemos um hub que centralizou conteúdos institucionais, integrou informações dos canais Fatos e Dados e do antigo Nossa Energia.",
          "A solução passou a permitir páginas formadas por componentes integrados de forma modular.",
        ],
      },
    ],
    evidence: [
      {
        _key: "nossa-energia-process-timeline",
        title: "Processo do projeto",
        caption: "Linha do processo: arquitetura de informação, naming, wireframes, conceitos, UI design, testes e lançamento.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-db6a1fd94175a10e867ce809028b52541b843712-1136x319-png",
          },
        },
      },
      {
        _key: "nossa-energia-content-structure",
        title: "Estruturação do hub de conteúdo",
        caption: "Mapeamento de conteúdo e organização para o hub editorial.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-61bfb117cab536b6e8b0b561c7b959d149b197a7-2367x1332-png",
          },
        },
      },
      {
        _key: "nossa-energia-channel-ecosystem",
        title: "Review do ecossistema de canais",
        caption: "Mapa do ecossistema de canais antes da reorganização do hub de conteúdo.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-a81d19570eb108c3ef40de47e88d8c1e6e03f01e-2367x1331-png",
          },
        },
      },
      {
        _key: "nossa-energia-hub-incorporation",
        title: "Incorporação de canais ao hub",
        caption: "Proposta de incorporação dos canais ao hub de conteúdo e ao site institucional.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-f537ee2cb8a7fd98d8e2f5ecadf8c3e30124fa03-2367x1332-png",
          },
        },
      },
      {
        _key: "nossa-energia-cover-mockup",
        title: "Mockup da home Nossa Energia",
        caption: "Mockup da home do portal Nossa Energia em notebook.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-c3128dce74501d01370318a34c55fdec42b4a076-3000x2250-png",
          },
        },
      },
      {
        _key: "nossa-energia-home-desktop",
        title: "Home Nossa Energia, desktop",
        caption: "Tela final desktop do portal editorial Nossa Energia.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-1db615c254587bd0aaa32d7aed276012024c7e99-2560x9562-png",
          },
        },
      },
      {
        _key: "nossa-energia-home-mobile",
        title: "Home Nossa Energia, mobile",
        caption: "Tela final mobile do portal editorial Nossa Energia.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-914b9709d0e693de80a521c0a1079978d58cd6df-720x16232-png",
          },
        },
      },
    ],
  },
  {
    _id: "caseStudy.petrobras-design-system",
    _type: "caseStudy",
    title: "Petrobras — Design System",
    slug: { _type: "slug", current: "petrobras-design-system" },
    client: "Petrobras",
    role: "Design System e documentação",
    status: "Finalizado",
    order: 40,
    stack: ["Figma", "Notion", "Design Tokens", "Specs"],
    summary:
      "Design System Petrobras v2 com tokens, componentes, seções, templates, motion, acessibilidade e documentação manual de specs para sustentar o ecossistema digital.",
    sections: [
      {
        _key: "fundacoes",
        eyebrow: "Fundações",
        title: "Uma biblioteca visual e uma documentação prática.",
        body: [
          "A documentação foi criada manualmente no Notion, incluindo tokens, componentes, anatomia, specs, estados e regras de uso.",
          "O objetivo era reduzir ambiguidade na implementação e criar uma linguagem comum para times diversos.",
        ],
      },
    ],
    evidence: [
      {
        _key: "petro-ds-figma-cover",
        title: "Arquivo PetroDS v2 no Figma",
        caption: "Visão da capa do arquivo PetroDS v2 no Figma, com navegação lateral de tokens e componentes.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-2f37b993cd9cb58cdc0d71a59248baa496cf194d-3840x2026-png",
          },
        },
      },
      {
        _key: "petro-ds-colors",
        title: "Tokens de cores",
        caption: "Documentação dos tokens de cores da marca no PetroDS v2.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-3b0e797f0dae611b733f275dd36b501b6a398400-3840x2026-png",
          },
        },
      },
      {
        _key: "petro-ds-template-level-2",
        title: "Template de página nível 2",
        caption: "Template nível 2 documentado em variações default e high contrast.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-389c19aae13998380783cdbf2c63e49d6a41734a-3840x2026-png",
          },
        },
      },
      {
        _key: "petro-ds-link-component",
        title: "Componente Link",
        caption: "Documentação do componente Link em desktop e mobile, com variações default e high contrast.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-c490b14bc4e21b11034fbd6c52bc6d4d91793425-3840x2026-png",
          },
        },
      },
      {
        _key: "petro-ds-theme-variables",
        title: "Variáveis de tema",
        caption: "Coleções de variáveis do PetroDS v2 organizadas por temas default e high contrast.",
        image: {
          _type: "image",
          asset: {
            _type: "reference",
            _ref: "image-314d20d0601656ccedc30aa3b63fe27192bf0805-3840x2026-png",
          },
        },
      },
    ],
  },
];
