export const portfolioProjects = [
  {
    _id: "portfolioProject.clinia",
    _type: "portfolioProject",
    title: "Clinia",
    id: { _type: "slug", current: "clinia" },
    group: "portfolio",
    featured: true,
    order: 10,
    tags: ["AI, Saúde, CRM", "Em andamento"],
    description: "Site, Plataforma, Design System",
    href: "/clinia",
    type: "Web app",
    status: "Em andamento",
    summary: "Produto de saúde digital com CRM, experiências com IA e design system.",
    deliverables: ["UI", "UX", "Design System", "AI", "Research"],
  },
  {
    _id: "portfolioProject.talqui",
    _type: "portfolioProject",
    title: "Talqui",
    id: { _type: "slug", current: "talqui" },
    group: "portfolio",
    featured: true,
    order: 20,
    tags: ["AI, Provedores, Chat", "Em andamento"],
    description: "Site, Plataforma, Design System",
    href: "/cases/talqui",
    type: "Web app",
    status: "Em andamento",
    summary: "Plataforma de atendimento com IA, redesign, design system e site em Framer.",
    deliverables: ["UI", "UX", "Design System", "No code", "AI"],
  },
  {
    _id: "portfolioProject.petrobras",
    _type: "portfolioProject",
    title: "Petrobras",
    id: { _type: "slug", current: "petrobras" },
    group: "portfolio",
    featured: true,
    order: 30,
    tags: ["Institucional", "2022 - 2024"],
    description: "Site, Portal de Conteúdos, Design System",
    href: "/petrobras",
    type: "Site",
    status: "Case disponível",
    summary: "Portal Nossa Energia, site institucional e Design System Petrobras v2.",
    deliverables: ["UI", "UX", "Design System", "Motion", "Research"],
  },
  {
    _id: "portfolioProject.orcamais",
    _type: "portfolioProject",
    title: "Orçamais",
    id: { _type: "slug", current: "orcamais" },
    group: "portfolio",
    featured: true,
    order: 40,
    tags: ["AI, Obras, SaaS", "Em andamento"],
    description: "Plataforma de gestão de obras pela Versare",
    type: "Web app",
    status: "Em andamento",
    summary: "Plataforma de gestão de obras construída pela Versare com AI no processo.",
    deliverables: ["UI", "UX", "AI", "Design System"],
  },
  {
    _id: "portfolioProject.grupo-primo",
    _type: "portfolioProject",
    title: "Grupo Primo",
    id: { _type: "slug", current: "grupo-primo" },
    group: "portfolio",
    featured: true,
    order: 50,
    tags: ["Marketing, Finanças, Educacional", "2021 - 2022"],
    description: "Finclass, Staage, Staart, Design System e Landing Pages",
    type: "Site",
    status: "Finalizado",
    summary: "Produtos digitais de educação e conteúdo como Finclass, Staage e Staart.",
    deliverables: ["UI", "UX", "Design System"],
  },
  {
    _id: "portfolioProject.jstack",
    _type: "portfolioProject",
    title: "JStack",
    id: { _type: "slug", current: "jstack" },
    group: "portfolio",
    featured: false,
    order: 60,
    type: "Site",
    status: "Finalizado",
    summary: "Redesign institucional, posicionamento, landing pages e evolução de produto.",
    deliverables: ["UI", "UX", "No code", "Design System"],
  },
  {
    _id: "portfolioProject.grana-ai",
    _type: "portfolioProject",
    title: "Grana.ai",
    id: { _type: "slug", current: "grana-ai" },
    group: "portfolio",
    featured: false,
    order: 70,
    type: "Web app",
    status: "Versare",
    summary: "Produto financeiro com foco em clareza, jornadas e experiência de uso.",
    deliverables: ["UI", "UX", "AI"],
  },
  {
    _id: "portfolioProject.docompliance",
    _type: "portfolioProject",
    title: "Docompliance",
    id: { _type: "slug", current: "docompliance" },
    group: "portfolio",
    featured: false,
    order: 80,
    type: "Web app",
    status: "Versare",
    summary: "Plataforma jurídica com IA para fluxos de compliance e operação.",
    deliverables: ["UI", "UX", "AI", "Design System"],
  },
  {
    _id: "portfolioProject.gennio",
    _type: "portfolioProject",
    title: "Gennio",
    id: { _type: "slug", current: "gennio" },
    group: "portfolio",
    featured: false,
    order: 90,
    type: "Site",
    status: "Versare",
    summary: "Landing pages e presença digital para comunicação de produto.",
    deliverables: ["UI", "No code"],
  },
  {
    _id: "portfolioProject.velloo",
    _type: "portfolioProject",
    title: "Velloo",
    id: { _type: "slug", current: "velloo" },
    group: "portfolio",
    featured: false,
    order: 100,
    type: "App",
    status: "Versare",
    summary: "Experiência mobile com foco em interface, fluxos e produto.",
    deliverables: ["UI", "UX"],
  },
  {
    _id: "portfolioProject.marmaris",
    _type: "portfolioProject",
    title: "Marmaris",
    id: { _type: "slug", current: "marmaris" },
    group: "portfolio",
    featured: false,
    order: 110,
    type: "Site",
    status: "Versare",
    summary: "Site institucional com direção visual e experiência responsiva.",
    deliverables: ["UI", "UX", "No code"],
  },
  {
    _id: "portfolioProject.clinia-platform",
    _type: "portfolioProject",
    title: "Plataforma",
    id: { _type: "slug", current: "clinia-platform" },
    group: "clinia",
    order: 10,
    eyebrow: "Web App",
    description:
      "Nova base da plataforma Clinia: versão 2.0, onboarding, estatísticas, CRM, design system e fluxo design-to-code com Cursor e Claude.",
    href: "/cases/clinia",
    status: "Case disponível",
    type: "Web app",
  },
  {
    _id: "portfolioProject.clinia-site",
    _type: "portfolioProject",
    title: "Site",
    id: { _type: "slug", current: "clinia-site" },
    group: "clinia",
    order: 20,
    eyebrow: "Pricing",
    description: "Frente do site institucional, incluindo a página de Pricing para comunicar planos, valor e conversão comercial.",
    status: "Em andamento",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-nossa-energia",
    _type: "portfolioProject",
    title: "Nossa Energia",
    id: { _type: "slug", current: "petrobras-nossa-energia" },
    group: "petrobras",
    order: 10,
    eyebrow: "Portal de conteúdos",
    description:
      "Hub editorial da Petrobras para centralizar conteúdos institucionais, artigos e editorias usando componentes do design system.",
    href: "/cases/petrobras-nossa-energia",
    status: "Case disponível",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-design-system",
    _type: "portfolioProject",
    title: "Design System Petrobras",
    id: { _type: "slug", current: "petrobras-design-system" },
    group: "petrobras",
    order: 20,
    eyebrow: "Fundação do ecossistema",
    description:
      "Biblioteca documentada manualmente com tokens, componentes, seções, templates, motion e specs para sustentar o ecossistema digital.",
    href: "/cases/petrobras-design-system",
    status: "Case disponível",
    type: "Site",
  },
  {
    _id: "portfolioProject.petrobras-main-site",
    _type: "portfolioProject",
    title: "Site principal",
    id: { _type: "slug", current: "petrobras-main-site" },
    group: "petrobras",
    order: 30,
    eyebrow: "petrobras.com.br",
    description: "Experiência institucional principal conectada ao mesmo sistema visual e aos mesmos padrões de componentes.",
    status: "Em breve",
    type: "Site",
  },
];

export const caseStudies = [
  {
    _id: "caseStudy.clinia-platform",
    _type: "caseStudy",
    title: "Clinia — Plataforma 2.0",
    slug: { _type: "slug", current: "clinia" },
    client: "Clinia",
    role: "Product Design, Design System e Frontend",
    status: "Projeto em andamento",
    order: 10,
    stack: ["Figma", "shadcn", "Cursor", "Claude", "Figma MCP"],
    summary:
      "Construção da versão 2.0 da plataforma Clinia, conectando auditoria de UX, design system, shadcn customizado, protótipos reais com IA e fluxo design-to-code.",
    sections: [
      {
        _key: "contexto",
        eyebrow: "Contexto",
        title: "A versão 2.0 começou pelo entendimento do problema.",
        body: [
          "Entrei na Clinia com o objetivo de auxiliar na construção da versão 2.0 da plataforma. Antes de propor telas ou componentes, o primeiro passo foi entender as dores, gargalos e o motivo de criar uma nova versão em um produto que já existia.",
          "A nova Clinia nasce com uma tecnologia mais moderna e uma base mais escalável. A versão anterior tinha uma experiência visual menos alinhada ao momento atual da empresa e uma estrutura que dificultava evolução.",
        ],
      },
      {
        _key: "design-system",
        eyebrow: "Design System",
        title: "shadcn customizado para a identidade da Clinia.",
        body: [
          "A empresa já tinha uma direção visual desejada e alguns frameworks de front considerados. A decisão foi seguir com shadcn e adaptar toda a estrutura do Figma para atender a identidade visual da Clinia.",
          "Depois da estrutura no Figma, os mesmos componentes foram criados em código com Cursor, aproximando o trabalho de design da implementação real.",
        ],
      },
      {
        _key: "ia",
        eyebrow: "IA no processo",
        title: "Claude, Cursor e MCP do Figma no fluxo.",
        body: [
          "Usamos Claude, Cursor e MCP do Figma para criar protótipos reais sincronizados com as interfaces do Figma.",
          "O objetivo é reduzir a distância entre decisão de design, validação de fluxo e implementação.",
        ],
      },
    ],
  },
  {
    _id: "caseStudy.talqui-platform",
    _type: "caseStudy",
    title: "Talqui — Plataforma",
    slug: { _type: "slug", current: "talqui" },
    client: "Talqui",
    role: "Product Design e Design System",
    status: "Projeto em andamento",
    order: 20,
    stack: ["Figma", "Design Tokens", "Storybook", "IA"],
    summary:
      "Reconstrução da plataforma Talqui a partir de uma interface antiga criada como fork técnico, criando identidade própria, design system, tokens personalizados e documentação em Storybook.",
    sections: [
      {
        _key: "contexto",
        eyebrow: "Contexto",
        title: "A plataforma precisava deixar de parecer uma adaptação técnica.",
        body: [
          "Na Talqui, construí toda a plataforma nova, desde o Design System até as novas telas.",
          "A versão antiga era um fork de uma interface criada pelos devs. O objetivo passou a ser criar uma identidade de plataforma alinhada à marca.",
        ],
      },
      {
        _key: "escala",
        eyebrow: "Escala",
        title: "Tokens, componentes e Storybook como base viva.",
        body: [
          "Construímos o DS pensando em escala, com variáveis, design tokens e componentes preparados para novas atualizações.",
          "Os devs criaram um repositório para o design system e sincronizam a documentação com Storybook, tornando o projeto mais escalável.",
        ],
      },
    ],
  },
  {
    _id: "caseStudy.petrobras-nossa-energia",
    _type: "caseStudy",
    title: "Petrobras — Nossa Energia",
    slug: { _type: "slug", current: "petrobras-nossa-energia" },
    client: "Petrobras",
    role: "Design System, UX, UI e Liferay collaboration",
    status: "Finalizado",
    order: 30,
    stack: ["Figma", "Liferay CMS", "Design System", "UX"],
    summary:
      "Portal editorial para centralizar conteúdos institucionais da Petrobras, usando o Design System Petrobras v2 e uma arquitetura de informação mais clara para publicação.",
    sections: [
      {
        _key: "desafio",
        eyebrow: "Desafio",
        title: "Centralizar conteúdos sem perder consistência.",
        body: [
          "A necessidade era centralizar conteúdos institucionais e artigos da Petrobras porque esses conteúdos estavam dispersos em canais distintos.",
          "Além disso, a transição tecnológica para CMS Liferay era essencial para oferecer aos publicadores uma experiência mais autônoma e eficiente.",
        ],
      },
      {
        _key: "solucao",
        eyebrow: "Solução",
        title: "Um hub editorial conectado ao design system.",
        body: [
          "Desenvolvemos um hub que centralizou conteúdos institucionais, integrou informações dos canais Fatos e Dados e do antigo Nossa Energia.",
          "A solução passou a permitir páginas formadas por componentes integrados de forma modular.",
        ],
      },
    ],
  },
  {
    _id: "caseStudy.petrobras-design-system",
    _type: "caseStudy",
    title: "Petrobras — Design System",
    slug: { _type: "slug", current: "petrobras-design-system" },
    client: "Petrobras",
    role: "Design System e documentação",
    status: "Finalizado",
    order: 40,
    stack: ["Figma", "Notion", "Design Tokens", "Specs"],
    summary:
      "Design System Petrobras v2 com tokens, componentes, seções, templates, motion, acessibilidade e documentação manual de specs para sustentar o ecossistema digital.",
    sections: [
      {
        _key: "fundacoes",
        eyebrow: "Fundações",
        title: "Uma biblioteca visual e uma documentação prática.",
        body: [
          "A documentação foi criada manualmente no Notion, incluindo tokens, componentes, anatomia, specs, estados e regras de uso.",
          "O objetivo era reduzir ambiguidade na implementação e criar uma linguagem comum para times diversos.",
        ],
      },
    ],
  },
];
